### ISSUE TITLE
NMF for Non-negative Constrained Least Squares

### ISSUE THREAD

**Issue by chsasank** [ctherien/pysptools#2]
Hi,

I have recently used NMF in sklearn for unmixing/end member detection and it was much faster compared to the implementation we have in pysptools.
We can use end member matrix U user provides and UCLS result as custom initialisation for NMF. It gives excellent results.

Shall we implement this?

Sasank.

**Comment by ctherien** [comment]
Hi Sasank,

If it's faster, why not. We can exchange code by email or create a github
project for ideas to test. The former is easier I think.

Bye

2016-04-19 4:09 GMT-04:00 Sasank Chilamkurthy notifications@github.com:

**Comment by chsasank** [comment]
I'll create a branch and raise a pull request.

**Comment by ctherien** [comment]
ok, I will see in the next days

2016-04-22 1:59 GMT-04:00 Sasank Chilamkurthy notifications@github.com:
