### ISSUE TITLE
Please Provide an example of pysptools.classification.sam

### ISSUE THREAD

**Issue by Pruthvi3796** [ctherien/pysptools#3]
What is the m,n,p,N and E in this?
classify(M, E, threshold=0.1, mask=None)
Classify the HSI cube M with the spectral library E.

Parameters:	
M – numpy array A HSI cube (m x n x p).
E – numpy array A spectral library (N x p).
threshold –
float [default 0.1] or list * If float, threshold is applied on all the spectra. * If a list, individual threshold is applied on each

spectrum, in this case the list must have the same number of threshold values than the number of spectra.
Threshold have values between 0.0 and 1.0.
mask – numpy array [default None] A binary mask, when True the selected pixel is classified.
Please Provide an example if possible

**Comment by ctherien** [comment]
m is the vertical of a hyperspectral image
n is the horizontal
p is the number of bands
N is a hyperspectral cube (image) (m x n x p)
E is a set of spectrum

For sam example: check the doc in the examples section: Smokestack
Effluents Analysis

2017-04-06 6:47 GMT-04:00 Pruthvi3796 <notifications@github.com>:

**Comment by Pruthvi3796** [comment]
I have spectral library created in ENVI. How can i read it or fit it in this pysptools 's SAM classifier.Please give me example of read spectral library created in ENVI for SAM

**Comment by ctherien** [comment]
Check the file pysptools.util.envi.py
All examples load ENVI files

2017-04-06 11:59 GMT-04:00 Pruthvi3796 <notifications@github.com>:

**Comment by Pruthvi3796** [comment]
I am doing as above suggested.But it's gives error.
from pysptools.util import envi
sl=envi.load_ENVI_spec_lib("D:\Tree Discrimination\data\speclib.sli")
then its gives error:File does not appear to be ENVI header(appears to be a binary header)

**Comment by ctherien** [comment]
The function load_ENVI_spec use the spectral library. You need to read the
spectral lib doc and do some tests. This library accept only a few ENVI
file suffix.

2017-04-07 2:43 GMT-04:00 Pruthvi3796 <notifications@github.com>:

**Comment by Pruthvi3796** [comment]
I did classification like below.
```
from pysptools.util import envi as ev
from pysptools.classification import SAM as sm
import numpy as np
import gdal
d=ev.load_ENVI_spec_lib("D:\data\speclib.hdr")
img=gdal.Open("D:\data\sub_66")
M=img.ReadAsArray()
n1=d[0]
n2=d[1]
n1=np.transpose(n1)
wavelength=n2['wavelength']
wavelength=np.float64(wavelength)
E=np.column_stack((wavelength,n1))
class1=sm.classify(M,E,thresold=0.1)
```
But it gives error like this

TypeError: unbound method classify() must be called with SAM instance as first argument (got ndarray instance instead) What is the problem? M - is ndarray of hyperspectral image E - is ndarray of spectral library consist 5 column(wavelength,spectra1,spectra2..spectra4)

**Comment by Pruthvi3796** [comment]
I did classification like below.

```
from pysptools.util import envi as ev
from pysptools.classification import SAM as sm
import numpy as np
import gdal
d=ev.load_ENVI_spec_lib("D:\data\speclib.hdr")
img=gdal.Open("D:\data\sub_66")
M=img.ReadAsArray()
n1=d[0]
n2=d[1]
n1=np.transpose(n1)
wavelength=n2['wavelength']
wavelength=np.float64(wavelength)
E=np.column_stack((wavelength,n1))
class1=sm.classify(M,E,thresold=0.1)
```
But it gives error like this

TypeError: unbound method classify() must be called with SAM instance as first argument (got ndarray instance instead) What is the problem? M - is ndarray of hyperspectral image E - is ndarray of spectral library consist 5 column(wavelength,spectra1,spectra2..spectra4)

**Comment by ctherien** [comment]
Pass it like this: E=[spectra1 spectra2 spectra3], wavelength are implicit

2017-04-08 11:48 GMT-04:00 Pruthvi3796 <notifications@github.com>:

**Comment by Pruthvi3796** [comment]
Though,It gives an error like TypeError: unbound method classify() must be called with SAM instance as first argument (got ndarray instance instead)

**Comment by Pruthvi3796** [comment]
I solved the above said issue.But one another question is how to save the classification image?
